version: '3'
services:
  app1:
    container_name: app1
    image: "${ECR_IMAGE}"
    ports:
      - "8080:8080"
    networks:
      - app-network

  app2:
    container_name: app2
    image: "${ECR_IMAGE}"
    ports:
      - "8081:8080"
    networks:
      - app-network

  app3:
    container_name: app3
    image: "${ECR_IMAGE}"
    ports:
      - "8082:8080"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app1
      - app2
      - app3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - app-network

networks:
  app-network:
