services:
  mysql:
    container_name: supportdb
    image: mysql:8.2
    volumes:
      - supportdb:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: support
      MYSQL_ROOT_PASSWORD: 1234

#  rabbitmq:
#    image: rabbitmq:3-management-alpine
#    container_name: rabbitmq-stream
#    volumes:
#      - rabbitmq:/etc/rabbitmq/
#      - rabbitmq:/var/lib/rabbitmq/
#      - rabbitmq:/var/log/rabbitmq/
#    ports:
#      - "5672:5672"
#      - "15672:15672"
#    environment:
#      RABBITMQ_ERLANG_COOKIE: "RabbitMQ-Cookies"
#      RABBITMQ_DEFAULT_USER: "admin"
#      RABBITMQ_DEFAULT_PASS: "1234"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
volumes:
  supportdb:
#  rabbitmq:
