spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:8.2:///
    username: root
    password: 1234
  data:
    redis:
      host: localhost
      port: 6379



decorator:
  datasource:
    p6spy:
      enable-logging: false
logging:
  level:
    org:
      springframework:
        jdbc: debug
